### ISSUE TITLE
Initial NOF 8 error

### ISSUE THREAD

**Issue by brentvee** [NakedObjectsGroup/NakedObjectsFramework#34]
Hey Richard,
Hope you're well.
I'm trying to test out NOF 8 but getting a little stuck.
I've used your NakedObjects.Template as a starting point, slowly bringing in my domain model and menus etc.
Everything is compiling but I'm getting the following error at runtime 
`Error message received from server
Message: The response from the client was not parseable as a RestfulObject json Representation
Code: undefined(-1)
Description: A software error has occurred on the server.`
There are only WARN messages in the log file.
Do you have any suggestions for where I can start troubleshooting?

Thanks

**Comment by richardpawson** [comment]
When you say you are "_slowly_ bringing in my domain model and menus " (emphasis added), I assume that means that you have been running OK right up until a certain point where you brought something else in and you got the run error.  In which case you need to look at what you brought in on that iteration, if necessary go back before then and bring in even less on that iteration.

More generally, the run error message indicates that this is a server side error.  So make sure you are running the server in debug and watch out for exceptions there.

**Comment by brentvee** [comment]
Hey Richard,
By slowly I meant it took me a while...
Unfortunately our domain model is an all-or-nothing reference of dependencies, nuget packages and application settings.
Let met first ask, can I use NOF 8 on a .Net 4.6+ project?

**Comment by richardpawson** [comment]
I don't think there should be any issue with running on .Net 4.6+.  I just tried switching the Template project to 4.6.1 and it ran fine.

**Comment by brentvee** [comment]
I'm not getting any exceptions in debug mode either. 
Any suggestions about where else I can try find the issue?

**Comment by richardpawson** [comment]
First establish whether the RO server started (I very much doubt it, though).  i.e. go directly to the Url you have specified in nakedobjects.config.ts e.g. const appPath = "http://localhost:59949/rest";  

Make sure you do this in a browser that can render JSON (e.g. Chrome with JSON View) -  otherwise you'll just get the 'do you want to save this file' message.  See if you get the RO home representation back.

Secondly I recall that I had a problem some months back where it wasn't starting and it appeared not to be throwing any exceptions  -  but it was,  The issue turned out to be some non-obvious setting in Visual Studio.  I think I found the answer here:
http://stackoverflow.com/questions/31549030/visual-studio-2015-break-on-unhandled-exceptions-not-working

**Comment by brentvee** [comment]
I'm making some progress.
Finally managed to get one of my menus to show.
When clicking on the menu I'm getting this error
`Error message received from server
Message: Object must implement IConvertible.
Code: InternalServerError(500)
Description: A software error has occurred on the server.
Stack Trace :
at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
at System.Convert.ChangeType(Object value, Type conversionType)
at NakedObjects.Facade.Impl.Implementation.OidTranslatorSlashSeparatedTypeAndIds.KeyRepresentation(Object obj)
at NakedObjects.Facade.Impl.Implementation.OidTranslatorSlashSeparatedTypeAndIds.<>c__DisplayClass7_0.<GetKeyValues>b__0(PropertyInfo pi)
at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at NakedObjects.Facade.Impl.Implementation.OidTranslatorSlashSeparatedTypeAndIds.GetKeyValues(IObjectFacade nakedObjectForKey)
at NakedObjects.Facade.Impl.Implementation.OidTranslatorSlashSeparatedTypeAndIds.GetCodeAndKeyAsTuple(IObjectFacade nakedObject)
at NakedObjects.Facade.Impl.Implementation.OidTranslatorSlashSeparatedTypeAndIds.GetOidTranslation(IObjectFacade objectFacade)
at NakedObjects.Rest.Snapshot.Utility.UriMtHelper..ctor(IOidStrategy oidStrategy, HttpRequestMessage req, IObjectFacade objectFacade)
at NakedObjects.Rest.Snapshot.Utility.RestUtils.<>c__DisplayClass7_0.<GetChoiceValue>b__0()
at NakedObjects.Rest.Snapshot.Utility.RestUtils.GetChoiceValue(IOidStrategy oidStrategy, IObjectFacade item, Func`1 relType, RestControlFlags flags)
at NakedObjects.Rest.Snapshot.Utility.RestUtils.GetChoiceValue(IOidStrategy oidStrategy, HttpRequestMessage req, IObjectFacade item, IActionParameterFacade parameter, RestControlFlags flags)
at NakedObjects.Rest.Snapshot.Representations.ParameterRepresentation.<>c__DisplayClass21_0.<Create>b__0(IObjectFacade c)
at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at NakedObjects.Rest.Snapshot.Representations.ParameterRepresentation.Create(IOidStrategy oidStrategy, HttpRequestMessage req, IObjectFacade objectFacade, IActionParameterFacade parameter, RestControlFlags flags)
at NakedObjects.Rest.Snapshot.Strategies.AbstractActionRepresentationStrategy.GetParameter(IActionParameterFacade parameter)
at NakedObjects.Rest.Snapshot.Strategies.AbstractActionRepresentationStrategy.<GetParameterList>b__16_0(ParameterContextFacade p)
at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
at NakedObjects.Rest.Snapshot.Strategies.AbstractActionRepresentationStrategy.GetParameters()
at NakedObjects.Rest.Snapshot.Representations.InlineActionRepresentation.Create(IOidStrategy oidStrategy, HttpRequestMessage req, ActionContextFacade actionContext, RestControlFlags flags)
at NakedObjects.Rest.Snapshot.Representations.MenuRepresentation.<>c__DisplayClass27_0.<SetMembers>b__2(Tuple`2 a)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at NakedObjects.Rest.Snapshot.Representations.MenuRepresentation.SetMembers(IMenuFacade menu, HttpRequestMessage req, List`1 tempLinks)
at NakedObjects.Rest.Snapshot.Representations.MenuRepresentation.SetLinksAndMembers(HttpRequestMessage req, IMenuFacade menu)
at NakedObjects.Rest.Snapshot.Representations.MenuRepresentation..ctor(IOidStrategy oidStrategy, HttpRequestMessage req, IMenuFacade menu, RestControlFlags flags)
at NakedObjects.Rest.Snapshot.Representations.MenuRepresentation.Create(IOidStrategy oidStrategy, IMenuFacade menu, HttpRequestMessage req, RestControlFlags flags)
at NakedObjects.Rest.Snapshot.Utility.RestSnapshot.<>c__DisplayClass10_0.<.ctor>b__0()
at NakedObjects.Rest.Snapshot.Utility.RestSnapshot.Populate()
`

**Comment by richardpawson** [comment]
I've never seen that error before  -  or anything like it.  Looking at the stack trace it is trying to create a string representation of the key (or one of the keys) for some object and it implies that that particular key doesn't implement IConvertable. This is not an interface I'm very familiar with, but it appears to be necessary in order to work with the Convert.ChangeType method, thus:

return (string) Convert.ChangeType(obj, typeof(string));

This suggests that your key isn't one of the more common types used for keys (string, int, date etc).  Are you using unusual types for any of your object keys?  

You might end up having to bring in the NOF source code and set a break point where that error is being thrown -  to see what the type of the object it is trying to convert into a string key is.

**Comment by brentvee** [comment]
Hmm.
We are using GUID's as our Entity primary keys

**Comment by richardpawson** [comment]
Doing some further reading, I discover that Guid does not implement IConvertable, so I'm guessing that is what you are using.  We probably don't have any tests that involve using Guids as object keys.  I will try to test this scenario, this week if possible, and get back to you.  I know that historically NOF has supported Guid keys  -  and if this is now failing in NOF8 (because the use of keys in Urls is now very different) then it should be fairly easy for us to fix.  Meantime, please confirm if you are using Guids.

**Comment by brentvee** [comment]
Indeed we are using Guid's.
Thanks Richard.

**Comment by richardpawson** [comment]
Brent.  I have just published an 8.0.2 version of the NakedObjects.Facade.Impl package only, which I hope fixes the issue with Guid keys.  Please could you try it out and report if it works for you, as soon as possible. You need only upgrade that one package.  (NakedObjects.Rest is now at 8.0.1  -  you might as well upgrade that one too to be on the latest code, though that addressed an unrelated issue).
