### ISSUE TITLE
NOF 7 Edit Form

### ISSUE THREAD

**Issue by brentvee** [NakedObjectsGroup/NakedObjectsFramework#40]
Hey Richard,
Hope you're well.
I have been trying to get our ObjectEdit view to look similar to our ObjectView view. So far so good,
but I'm getting a strange error when trying to Save the ObjectEdit.
We have some additional html elements like fieldsets and bootstrap rows/columns in our ObjectEdit view. (purely for separating the input controls)

This error is thrown from the GenericController.Edit 
StartIndex cannot be less than zero.<br>Parameter name: startIndex

> System.ArgumentOutOfRangeException was unhandled by user code
  HResult=-2146233086
  Message=StartIndex cannot be less than zero.
Parameter name: startIndex
  ParamName=startIndex
  Source=mscorlib
  StackTrace:
       at ResQ.Nickel.Portal.Controllers.GenericController.Edit(ObjectAndControlData controlData, FormCollection form) in GenericController.cs:line 
 130
       at lambda_method(Closure , ControllerBase , Object[] )
       at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
       at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
  InnerException:

**Comment by brentvee** [comment]
For each fieldset we want, we call `Html.PropertyListEditWith(Model,columsForFieldset)`
So in this example we call it twice

**Comment by richardpawson** [comment]
Dear BrentPlease also note that our priority is now on providing support for NOF8 (and we are already starting work on NOF9).I also note that you posted an issue with NOF8.  I responded to that very quickly and issued a new release of NOF8 within 24 hours, asking you to try it out and confirm if it now worked for you  -  but have so far had no further response from you on that.Kind regardsRichardOn 30 August 2016 at 09:19 brentvee <notifications@github.com> wrote:Hey Richard, Hope you're well. I have been trying to get our ObjectEdit view to look similar to our ObjectView view. So far so good, but I'm getting a strange error when trying to Save the ObjectEdit.This error is thrown from the GenericController.Edit  StartIndex cannot be less than zero.Parameter name: startIndexWe have some additional html elements like fieldsets and bootstrap rows/columns in our ObjectEdit view. (purely for separating the input controls)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by brentvee** [comment]
Apologies Richard,
Priorities shifted and I just haven't had the time to continue testing NOF8.
I hope to get back to it soon.
Many thanks
