### ISSUE TITLE
Not currently possible to add to an n:n association in Naked Functions

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#444]
I am still having difficulty with persisted n:n associations in Naked Functions. I _can_ get the following to work _though the UI_:

- Retrieve both ends of the association correctly, based on the data in the link table
- Remove associations

However, currently I can only add an association by inserting a row into the link table _directly through the database_ but I cannot do it through the UI. After some investigation now I don't believe this is currently possible because:

- If I just add an into the collection at one end, no error occurs, but no entry in the Link table is added. I _suspect_ this is because I am (correctly to follow the functional style) updating the object with a _new_ collection - copied from the old one but with new element added. I think this results in EF not tracking the change. 

- The other way to do it would be to add a row into the Link table, by creating an unseen `Link `object mapped to it. The problem here is that when you create the new Link instance you must specify the keys. But then when calling `context.WithNew(newLink) `NOF protests (understandably) that the object already has a key e.g.

```
Message: Save object Student:3 Group: 4 already has a key,
Code: InternalServerError(500)
Description: A software error has occurred on the server.
Stack Trace :
at NakedFramework.Persistor.EFCore.Component.EFCoreDetachedObjectCommand.ValidateDetachedObjects()
at NakedFramework.Persistor.EFCore.Component.EFCoreDetachedObjectCommand.Execute()
at NakedFramework.Persistor.EFCore.Component.EFCoreObjectStore.Execute(EFCoreDetachedObjectCommand cmd)
at NakedFramework.Persistor.EFCore.Component.EFCoreObjectStore.ExecuteDetachedObjectCommand(IDetachedObjects objects)
at NakedFramework.Persistor.EFCore.Component.EFCoreObjectStore.UpdateDetachedObjects(IDetachedObjects objects)
at NakedFramework.Core.Component.ObjectPersistor.UpdateDetachedObjects(IDetachedObjects objects)
at NakedFramework.Core.Component.LifeCycleManager.Persist(IDetachedObjects objects)
```
 
- (There is no point, I have discovered, attempting to specify that the Link does not have a key - as EF protests that a change-tracked entity must have a key, nor in specifying that _neither_ column defining the (compound) PK of Link has auto-generated values (NOF protests as before).

Unless you can find a way to do this now, my current thinking is that we need a new Naked Functions attribute, that could to be applied to the Link class, specifying that a new instance of this type may (indeed _must_) be provided with key values specified by the domain code. Possible names:

`[LinkType]`  but is that a hostage to fortune?

`[KeyAlwaysProvidedByDomainCode]` clearer, but a bit long-winded.

`[UserManagedKey]`  ?

Should be applied at class level, or to the key field, or **fields** ?

**Separate consideration - 1:n collections in Naked Functions**
Although not itself needing a framework change, this issue highlights an issue with 1:n associations. In our examples so far, the 'clone from' constructor typically copies a reference to the existing collection. It shouldn't: it should make a new collection from the existing - as if the collection _were_ immutable - and use that in the clone. This means (I think) that adding to a collection will not then be tracked - which is no bad thing because adding to a collection is not FP. Instead, an object should be added to a collection - in a 1: n association - by updating the FK field on that object. This needs testing and documenting as the pattern for all multiple associations (so please assign back to RP when done).  

For discussion: If this is adopted, are we then able to use ImmutableList in associations?  Also: if we are always updating an object by cloning it first and then 're-attaching' it (in the context) do we still need the entities (in NF) to be 'change tracking' ?

**Comment by richardpawson** [comment]
Fixed (manually tested in MetalUp.Express app)
