### ISSUE TITLE
Failed to find spec..

### ISSUE THREAD

**Issue by brentvee** [NakedObjectsGroup/NakedObjectsFramework#5]
Hey Richard,

We're often receiving an exception saying "Failed to find spec for..."
To date, i've just gone and added the type explicitly to the Types as you told me before, but this time we have an abstract class with several concrete types.
Do i have to add each type explicitly, or is there some configuration I've missed that NOF is not introspecting?

Thanks.
Here is the stacktrace :

> NakedObjects.Core.NakedObjectSystemException was unhandled by user code
  HResult=-2146233088
  Message=failed to find spec for System.Linq.Enumerable+WhereEnumerableIterator`1[[ResQ.Nickel.Model.CaseManagement.NodeCaseRelationship, ResQ.Nickel.Model, Version=3.9.0.0, Culture=neutral, PublicKeyToken=null]]
  Source=NakedObjects.Metamodel
  StackTrace:
       at NakedObjects.Meta.Component.Metamodel.GetSpecification(Type type, Boolean allowNull)
       at NakedObjects.Core.Component.MetamodelManager.GetInnerSpec(Type type)
       at NakedObjects.Core.Component.MetamodelManager.GetSpecification(Type type)
       at NakedObjects.Core.Spec.OneToOneAssociationSpec.GetAssociation(INakedObjectAdapter fromObjectAdapter)
       at NakedObjects.Core.Spec.OneToOneAssociationSpec.GetNakedObject(INakedObjectAdapter fromObjectAdapter)
       at NakedObjects.Web.Mvc.Html.PropertyContext.GetValue(INakedObjectsFramework framework)
       at NakedObjects.Web.Mvc.Html.CommonHtmlHelper.GetFieldValue(HtmlHelper html, PropertyContext propertyContext, Boolean inTable)
       at NakedObjects.Web.Mvc.Html.CommonHtmlHelper.GetViewField(HtmlHelper html, PropertyContext propertyContext, String tooltip, Boolean addIcon, Boolean inTable)
       at NakedObjects.Web.Mvc.Html.CommonHtmlHelper.GetViewValue(HtmlHelper html, PropertyContext propertyContext)
       at NakedObjects.Web.Mvc.Html.CommonHtmlHelper.ViewObjectField(HtmlHelper html, PropertyContext propertyContext)
       at NakedObjects.Web.Mvc.Html.CommonHtmlHelper.<>c__DisplayClass72.<ViewObjectFields>b__71(IAssociationSpec property)
       at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
       at NakedObjects.Web.Mvc.Html.ElementDescriptor.BuildElementSet(IEnumerable`1 elements)
       at NakedObjects.Web.Mvc.Html.CommonHtmlHelper.AddClassAndIdToElementSet(IEnumerable`1 elements, String cls, String id)
       at NakedObjects.Web.Mvc.Html.CommonHtmlHelper.BuildViewContainer(HtmlHelper html, INakedObjectAdapter nakedObject, IEnumerable`1 elements, String cls, String id, Boolean anyEditableFields)
       at NakedObjects.Web.Mvc.Html.CommonHtmlHelper.PropertyListWithFilter(HtmlHelper html, Object domainObject, Func`2 filter, Func`2 order)
       at NakedObjects.Web.Mvc.Html.PropertyExtensions.PropertyList(HtmlHelper html, Object domainObject)

**Comment by richardpawson** [comment]
The principle is: can the reflector find the class by walking the graph from methods defined in services.  Sub-classes sometimes fail this principle because the actual sub-classes never appear directly as types in any method signature that the reflector can get to.  So they need to be explicitly registered as types.  Note, however, that it is very simple to use reflection to register those types.  For example you could use reflection to get all sub-types of AbstractFoo in the model assemblies and then register those types.  You can even use reflection to get all the domain types from your model and register them all.  There's no penalty from over-registering them.

**Comment by brentvee** [comment]
Ok, that makes sense
I've now added all the concrete types explicitly but still getting the same error
Any ideas?

**Comment by richardpawson** [comment]
Well it is obviously some other type. Either work out what types you've added to the model since you didn't have the problem. Or add get all the types from the assembly by reflection as I suggested.

**Comment by richardpawson** [comment]
You can use a method like this one _mutatis mutandis_:

```
private static Type[] Types {
    get {
var allTypes = AppDomain.CurrentDomain.GetAssemblies()
             .Single(a => a.GetName().Name == "AdventureWorksModel").GetTypes();
       return allTypes.Where(t => (t.BaseType == typeof(AWDomainObject)) &&  
             !t.IsAbstract).ToArray();
    }
}
```

**Comment by brentvee** [comment]
Many thanks Richard :+1:
